package udo.edu.game;



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import udo.edu.dbconnect.ConnectDB;
//import udo.edu.dbconnect.ConnectDB.Connect;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

   


/**
 *
 * @author Ninhc1010l, DCNguyen - edited by DCNguyen
 */
public class Game extends javax.swing.JFrame {
    //Get all questions then take one randomly

    public String answertotal = "";
    
    public String questiontotal = "";
    //Use variable error to check false guesses. error ==0 ->Lose
    public int error;
    public String answer = "";
    public String question = "";
    //Char array with its length = the length of answer. 
    public char[] cAnswer;
    StringBuffer bs;

    /** Creates new form game */
    public Game() {
        initComponents();
        setTitle("Hangman - Have fun with Hangman");
        initGame();
        loadquestion();
        setLocationRelativeTo(this);
    }
    
    public void initGame() {
        //Get data from the database
        // try block (with resources) will automatically close connections after using them //From Java 7
    	try(Connection conn = ConnectDB.getconnect();
    		Statement stmt = ConnectDB.getconnect().createStatement();
    		){
            	ResultSet rs = stmt.executeQuery("Select * from game");    
    			
            while (rs.next()) {
                //Add all the answers into answertotal 
                answertotal += rs.getString("Answer");
                answertotal += "|";
                //Add all the questions into questiontotal
                questiontotal += rs.getString("Question");
                questiontotal += "|";
            }
            //Create 2-dimensional array to split answers and questions
            String[] atemp;
            String[] qtemp;
            atemp = answertotal.split("\\|");
            qtemp = questiontotal.split("\\|");
            //Get a question and its answer randomly
            Random randomGenerator = new Random();
            int randomInt = randomGenerator.nextInt(atemp.length);
            //Get questions and answers randomly
            answer = new String(atemp[randomInt]);
            question = new String(qtemp[randomInt]);
            //Print a question
            lblquestion.setText(question);
            //Set the length of an answer
            cAnswer = new char[answer.length()];
        } catch (Exception e) {
            e.printStackTrace();
            }
         }
    
    //Load question

    public void loadquestion()  {
        initGame();
        //Maximum 9 wrong guesses (times) are allowed
        error = 9;
        lblstatus.setText("You have: " + error + " times left");
        for (int i = 0; i < cAnswer.length; i++) {
            cAnswer[i] = '*';
        }
        String str = new String(cAnswer);
        lblAnswer.setText(str);
        txtkey.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblAnswer = new javax.swing.JLabel();
        txtkey = new javax.swing.JTextField();
        btnok = new javax.swing.JButton();
        lblquestion = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblstatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Hangman game");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Question"));

        lblAnswer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAnswer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtkey.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter one character"));
        txtkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkeyActionPerformed(evt);
            }
        });
        txtkey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtkeyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkeyKeyReleased(evt);
            }
        });

        btnok.setText("OK");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        lblquestion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblquestion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("New Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(40)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(lblquestion, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(lblAnswer, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
        			.addGap(31)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(btnok, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(txtkey, GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
        				.addComponent(jButton1, GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(lblAnswer, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtkey, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(btnok)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jButton1)
        			.addPreferredGap(ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
        			.addComponent(lblquestion, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
        );
        jPanel1.setLayout(jPanel1Layout);

        lblstatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(180)
        					.addComponent(jLabel1))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(lblstatus, GroupLayout.PREFERRED_SIZE, 128, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 505, GroupLayout.PREFERRED_SIZE))))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addGap(29)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(lblstatus, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void txtkeyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkeyKeyReleased
	    //
	}//GEN-LAST:event_txtkeyKeyReleased
	
	private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
	    //Empty detected
    if (txtkey.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Please enter one letter !!!");
        txtkey.requestFocus();
        return;
    }
    //Only one letter is allowed
    if (txtkey.getText().length() > 1) {
        JOptionPane.showMessageDialog(this, "Only one letter is allowed");
        txtkey.setText("");
        txtkey.requestFocus();
        return;
    }
    //Check the position where the keyword appears
    int[] k = new int[answer.length()];
    //if count==0 =>> the character entered is not a keyword
    int count = 0;
    //Convert answer to array to check whether it contains keywords
    char[] c = answer.toCharArray();
    char keyword = txtkey.getText().charAt(0);
    //Use loop to check whether it contains character in an answer string
    for (int i = 0; i < c.length; i++) {
        if (Character.toLowerCase(c[i])==Character.toLowerCase(keyword)) {
            //nếu từ khóa xuất hiện trong answer ->> vị trí xuất hiện =i
            k[count] = i;
            count++;
        }
    }
    //count ==0, the times left must be reduced (one)
    if (count == 0) {
        error--;
        lblstatus.setText("You have: " + error + "times left");
    } else {
        
        //display the new string
        bs = new StringBuffer(lblAnswer.getText());
        for (int i = 0; i < count; i++) {
            bs.setCharAt(k[i], keyword);
        }
        lblAnswer.setText(bs.toString());
    }
    //Error == 0 -> Lose, then load a new game
    if (error < 1) {
        lblAnswer.setText(answer);
        JOptionPane.showMessageDialog(this, "You Lose !!!");
        
        loadquestion();
    }
    //if lblAnswer.getText = answer -> Win , load a new game
    if (lblAnswer.getText().equalsIgnoreCase(answer)) {
        JOptionPane.showMessageDialog(this, "You Win !!!");
        
        loadquestion();
    }
    txtkey.setText("");
    txtkey.requestFocus();
	}	//GEN-LAST:event_btnokActionPerformed

	private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
	}//GEN-LAST:event_formKeyReleased
	
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	    loadquestion();
	    txtkey.requestFocus();
	}//GEN-LAST:event_jButton1ActionPerformed
	
	private void txtkeyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkeyKeyPressed
	    //
	}//GEN-LAST:event_txtkeyKeyPressed

    private void txtkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkeyActionPerformed
        // TODO add your handling code here:
        btnok.doClick();
    }//GEN-LAST:event_txtkeyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Game().setVisible(true);
            }
        });
    }
    
    private javax.swing.JButton btnok;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnswer;
    private javax.swing.JLabel lblquestion;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JTextField txtkey;
    
}
